package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

//go:embed templates/*.html
var templateFS embed.FS

//go:embed static/*.css
var staticFS embed.FS

// basePath is an optional random path prefix (e.g. "/x7k9m2p4") every route
// is served under, set from PANEL_PATH_PREFIX in main(). It's read lazily by
// urlFor rather than passed through each handler, which is why it's safe for
// the package-level tmpl below to reference it before main() sets it: the
// closure only runs at template-execution time, after startup.
var basePath string

// urlFor prefixes an app-internal absolute path with basePath, so templates
// never hardcode a path that would work even if the prefix is guessed —
// every link, form action, and JS fetch target goes through this.
func urlFor(path string) string { return basePath + path }

var tmpl = template.Must(template.New("").Funcs(template.FuncMap{
	"url": urlFor,
	"t":   t,
	"tf": func(lang, key string, args ...any) string {
		return fmt.Sprintf(t(lang, key), args...)
	},
	"tHTML": func(lang, key string, args ...any) template.HTML {
		return template.HTML(fmt.Sprintf(t(lang, key), args...))
	},
	"langs": func() []langInfo { return supportedLangs },
}).ParseFS(templateFS, "templates/*.html"))

const (
	registryPath = "/opt/psi-panel/data/tunnels.json"
	configsDir   = "/opt/psi-panel/configs"
	dataDir      = "/opt/psi-panel/data"
	portBase     = 19000
	portMax      = 19999
)

type app struct {
	mu        sync.Mutex
	sessions  *sessionStore
	adminHash string
	creds     psiphonCreds
}

func main() {
	if len(os.Args) == 3 && os.Args[1] == "-hash-password" {
		hash, err := hashPassword(os.Args[2])
		if err != nil {
			log.Fatal(err)
		}
		os.Stdout.WriteString(hash + "\n")
		return
	}

	listenAddr := envOr("PANEL_LISTEN", "127.0.0.1:8443")
	adminHash := os.Getenv("PANEL_ADMIN_HASH")
	secretHex := os.Getenv("PANEL_SESSION_SECRET")
	basePath = strings.TrimSuffix(os.Getenv("PANEL_PATH_PREFIX"), "/")

	if adminHash == "" || secretHex == "" {
		log.Fatal("PANEL_ADMIN_HASH and PANEL_SESSION_SECRET must be set (see panel.env, generated by install.sh)")
	}

	a := &app{
		sessions:  newSessionStore([]byte(secretHex)),
		adminHash: adminHash,
		creds:     credsFromEnv(),
	}

	startUpdateChecker(1 * time.Hour)

	// Everything is served under basePath (e.g. "/x7k9m2p4") when
	// PANEL_PATH_PREFIX is set: a request to the bare "/" or "/login" then
	// hits nothing registered on this mux and gets net/http's generic 404,
	// same as any other unknown path — this is what actually hides the
	// panel from scanners hitting the raw port, not just cosmetic.
	mux := http.NewServeMux()
	// http.FileServer looks up paths against the embedded FS as-is (which
	// still has its original "static/..." layout); StripPrefix removes only
	// basePath from the incoming request so what's left ("/static/...")
	// matches that layout again, same as when basePath is empty.
	mux.Handle(basePath+"/static/", http.StripPrefix(basePath, http.FileServer(http.FS(staticFS))))
	mux.HandleFunc(basePath+"/login", a.handleLogin)
	mux.HandleFunc(basePath+"/logout", a.requireAuth(a.handleLogout))
	mux.HandleFunc(basePath+"/", a.requireAuth(a.handleDashboard))
	mux.HandleFunc(basePath+"/tunnels-status", a.requireAuth(a.handleTunnelsStatus))
	mux.HandleFunc(basePath+"/tunnels/add", a.requireAuth(a.handleAdd))
	mux.HandleFunc(basePath+"/tunnels/", a.requireAuth(a.handleTunnelAction))
	mux.HandleFunc(basePath+"/settings", a.requireAuth(a.handleSettings))
	mux.HandleFunc(basePath+"/update", a.requireAuth(a.handleUpdateTrigger))

	log.Printf("psi-panel listening on %s, base path %q (localhost-management; SOCKS ports stay bound to 127.0.0.1 independently)", listenAddr, basePath)
	log.Fatal(http.ListenAndServe(listenAddr, mux))
}

func envOr(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func (a *app) requireAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !a.sessions.valid(r) {
			http.Redirect(w, r, urlFor("/login"), http.StatusSeeOther)
			return
		}
		next(w, r)
	}
}

// langData returns the fields every page-rendering template needs for
// language selection: the active code, text direction, the (optional)
// Google Fonts family for it, and the list of languages for the switcher.
func langData(r *http.Request) map[string]any {
	lang := currentLang(r)
	info := langInfoFor(lang)
	dir := "ltr"
	if info.RTL {
		dir = "rtl"
	}
	return map[string]any{"Lang": lang, "Dir": dir, "Font": info.Font, "Langs": supportedLangs}
}

func withLang(r *http.Request, extra map[string]any) map[string]any {
	data := langData(r)
	for k, v := range extra {
		data[k] = v
	}
	return data
}

func (a *app) handleLogin(w http.ResponseWriter, r *http.Request) {
	setLangCookie(w, r)
	if r.Method == http.MethodGet {
		tmpl.ExecuteTemplate(w, "login.html", withLang(r, nil))
		return
	}
	ip := clientIP(r)
	if !a.sessions.allowAttempt(ip) {
		tmpl.ExecuteTemplate(w, "login.html", withLang(r, map[string]any{"Error": t(currentLang(r), "login.error.locked")}))
		return
	}
	pw := r.FormValue("password")
	if !checkPassword(a.adminHash, pw) {
		a.sessions.recordFailure(ip)
		tmpl.ExecuteTemplate(w, "login.html", withLang(r, map[string]any{"Error": t(currentLang(r), "login.error.wrong")}))
		return
	}
	a.sessions.recordSuccess(ip)
	a.sessions.issue(w, r)
	http.Redirect(w, r, urlFor("/"), http.StatusSeeOther)
}

func (a *app) handleLogout(w http.ResponseWriter, r *http.Request) {
	a.sessions.clear(w)
	http.Redirect(w, r, urlFor("/login"), http.StatusSeeOther)
}

type regionOpt struct {
	Code  string
	Label string
}

type row struct {
	Name        string
	Region      string
	SocksPort   int
	Status      string
	StatusClass string
	ExitRegion  string
	ExitFlagURL string
	Health      string // "ok", "fail", or "" when no probe result exists yet
	HealthAge   string
}

// buildRows computes each location's live status/exit info. Called both for
// the full dashboard render and for the /tunnels-status polling endpoint
// the page uses to pick up state changes (e.g. connecting -> active)
// without a manual reload.
func (a *app) buildRows() ([]row, error) {
	list, err := loadRegistry(registryPath)
	if err != nil {
		return nil, err
	}
	sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })

	health := readHealth()
	rows := make([]row, 0, len(list))
	for _, t := range list {
		info := tunnelStatusInfo(t.Name)
		class := "unknown"
		switch info.State {
		case "active":
			class = "active"
		case "connecting":
			class = "connecting"
		case "inactive", "failed":
			class = "inactive"
		}
		r := row{
			Name: t.Name, Region: regionLabel(t.Region), SocksPort: t.SocksPort,
			Status: info.State, StatusClass: class,
			ExitRegion: exitRegionLabel(info.Region), ExitFlagURL: flagImageURL(info.Region),
		}
		if h, ok := health[t.Name]; ok {
			r.Health = h.Result
			r.HealthAge = healthAge(h.Time)
		}
		rows = append(rows, r)
	}
	return rows, nil
}

func (a *app) handleDashboard(w http.ResponseWriter, r *http.Request) {
	setLangCookie(w, r)
	a.mu.Lock()
	defer a.mu.Unlock()

	rows, err := a.buildRows()
	if err != nil {
		http.Error(w, "failed to load tunnels: "+err.Error(), 500)
		return
	}

	regions := make([]regionOpt, 0, len(regionCodes))
	for code, label := range regionCodes {
		regions = append(regions, regionOpt{Code: code, Label: label})
	}
	sort.Slice(regions, func(i, j int) bool { return regions[i].Label < regions[j].Label })

	latest, available, _, _ := updates.snapshot()
	tmpl.ExecuteTemplate(w, "dashboard.html", withLang(r, map[string]any{
		"Tunnels":         rows,
		"Regions":         regions,
		"CurrentVersion":  CurrentVersion,
		"LatestVersion":   latest,
		"UpdateAvailable": available,
	}))
}

// handleUpdateTrigger starts the self-update script (via the narrowly
// scoped sudoers rule in install.sh's setup_sudo_control) and returns
// immediately — the update restarts the panel process partway through, so
// this can't wait for it to finish. See triggerSelfUpdate's comment for why
// output goes to a log file instead of this response.
func (a *app) handleUpdateTrigger(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", 405)
		return
	}
	if err := triggerSelfUpdate(); err != nil {
		http.Error(w, "failed to start update: "+err.Error(), 500)
		return
	}
	tmpl.ExecuteTemplate(w, "updating.html", withLang(r, nil))
}

// handleTunnelsStatus is a lightweight JSON polling endpoint the dashboard
// page calls every few seconds to update status badges and exit flags in
// place, without a full page reload.
func (a *app) handleTunnelsStatus(w http.ResponseWriter, r *http.Request) {
	a.mu.Lock()
	rows, err := a.buildRows()
	a.mu.Unlock()
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(rows)
}

// exitRegionLabel formats a connected server's region code for display —
// unlike regionLabel (which is for the Any/preference dropdown), an unknown
// code here is shown as-is rather than falling back to "Any", since Psiphon
// can connect through more regions than are in our curated egress-region
// dropdown list.
func exitRegionLabel(code string) string {
	if code == "" {
		return ""
	}
	if l, ok := regionCodes[code]; ok {
		return code + " - " + l
	}
	return code
}

func regionLabel(code string) string {
	if l, ok := regionCodes[code]; ok && code != "" {
		return code + " - " + l
	}
	return "Any"
}

func (a *app) handleAdd(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", 405)
		return
	}
	name := strings.TrimSpace(r.FormValue("name"))
	region := strings.TrimSpace(r.FormValue("region"))

	if !validName(name) {
		http.Error(w, "invalid name: use lowercase letters, digits, hyphens (2-31 chars)", 400)
		return
	}
	if _, ok := regionCodes[region]; !ok {
		http.Error(w, "invalid region", 400)
		return
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	list, err := loadRegistry(registryPath)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	for _, t := range list {
		if t.Name == name {
			http.Error(w, "a location with this name already exists", 409)
			return
		}
	}

	port, err := findFreePort(list, portBase, portMax)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}

	t := Tunnel{Name: name, Region: region, SocksPort: port}
	if err := writeTunnelConfig(configsDir, dataDir, t, a.creds); err != nil {
		http.Error(w, "failed writing config: "+err.Error(), 500)
		return
	}
	list = append(list, t)
	if err := saveRegistry(registryPath, list); err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	if err := startTunnel(name); err != nil {
		log.Printf("start %s: %v", name, err)
	}

	http.Redirect(w, r, urlFor("/"), http.StatusSeeOther)
}

func (a *app) handleSettings(w http.ResponseWriter, r *http.Request) {
	setLangCookie(w, r)
	a.mu.Lock()
	defer a.mu.Unlock()

	if r.Method == http.MethodPost {
		cfgJSON := r.FormValue("config_json")

		if err := validateExtraConfigJSON(cfgJSON); err != nil {
			tmpl.ExecuteTemplate(w, "settings.html", withLang(r, credsTemplateData(psiphonCreds{ConfigJSON: cfgJSON}, false, err.Error())))
			return
		}
		if err := saveExtraConfigJSON(cfgJSON); err != nil {
			http.Error(w, "failed saving: "+err.Error(), 500)
			return
		}
		a.creds = psiphonCreds{ConfigJSON: cfgJSON}
		tmpl.ExecuteTemplate(w, "settings.html", withLang(r, credsTemplateData(a.creds, true, "")))
		return
	}

	tmpl.ExecuteTemplate(w, "settings.html", withLang(r, credsTemplateData(a.creds, false, "")))
}

func credsTemplateData(c psiphonCreds, saved bool, errMsg string) map[string]any {
	return map[string]any{
		"ConfigJSON": c.ConfigJSON,
		"Saved":      saved,
		"Error":      errMsg,
	}
}

// /tunnels/<name>/<action> (under basePath, which must be stripped first —
// mux.HandleFunc doesn't strip a registered prefix from r.URL.Path the way
// http.StripPrefix-wrapped handlers do, so without this every request here
// carried an extra leading segment whenever PANEL_PATH_PREFIX was set,
// throwing off this exact-3-parts split entirely).
func (a *app) handleTunnelAction(w http.ResponseWriter, r *http.Request) {
	trimmed := strings.TrimPrefix(r.URL.Path, basePath)
	parts := strings.Split(strings.Trim(trimmed, "/"), "/")
	if len(parts) != 3 {
		http.NotFound(w, r)
		return
	}
	name, action := parts[1], parts[2]
	if !validName(name) {
		http.Error(w, "invalid name", 400)
		return
	}

	switch action {
	case "logs":
		out, _ := tunnelLogs(name, 200)
		tmpl.ExecuteTemplate(w, "logs.html", withLang(r, map[string]any{"Name": name, "Logs": out}))
		return
	case "restart":
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", 405)
			return
		}
		if err := restartTunnel(name); err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
	case "stop":
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", 405)
			return
		}
		if err := stopTunnel(name); err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
	case "remove":
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", 405)
			return
		}
		a.mu.Lock()
		defer a.mu.Unlock()
		stopTunnel(name)
		removeTunnelConfig(configsDir, name)
		os.RemoveAll(filepath.Join(dataDir, name))
		list, err := loadRegistry(registryPath)
		if err == nil {
			out := list[:0]
			for _, t := range list {
				if t.Name != name {
					out = append(out, t)
				}
			}
			saveRegistry(registryPath, out)
		}
	default:
		http.NotFound(w, r)
		return
	}
	http.Redirect(w, r, urlFor("/"), http.StatusSeeOther)
}
